export const SET_PAGE_VIEWED = 'SET_PAGE_VIEWED';
export const SET_USER = 'SET_USER';
export const SET_LOGIN_FORM_VALUE = 'SET_LOGIN_FORM_VALUE';
export const CLEAR_LOGIN_FORM = 'CLEAR_LOGIN_FORM';
export const SET_PROFILE_FORM_VALUE = 'SET_LOGIN_FORM_VALUE';
export const CLEAR_PROFILE_FORM = 'CLEAR_LOGIN_FORM';
export const SET_USER_ATTRIBUTE = 'SET_USER_ATTRIBUTE';
